// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package tutorial

type Proposal struct {
	ID string
}

type ProposalMeter struct {
	ID         int64
	ProposalID string
	M3terNo    int64
	Account    string
	Nonce      string
}
